name: Kernel module CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            linux-headers-$(uname -r) \
            sparse \
            clang-format \
            clang-tidy

      - name: Make scripts executable
        run: chmod +x ci/*.sh

      - name: Run all tests
        run: sudo ./ci/all.sh